<?php

namespace Fzr\Tool;

use Exception;

/**
 * Fzr Core Scaffolder
 *
 * プロジェクトのディレクトリ構造と初期ファイルをスケルトン（tools/stubs/skeleton/）から生成します。
 */
class Scaffolder
{
    const REPO_URL = 'https://github.com/t-ichi324/fzr-fw.git';

    public static function isInstalled(string $root, string $appPath = 'app'): bool
    {
        $app = trim($appPath, '/');
        return file_exists($root . '/' . $app . '/app.ini')
            || file_exists($root . '/app.ini');
    }

    public static function scaffold(array $d): array
    {
        $root = rtrim($d['path_root'] ?? '', '/\\');
        if (!$root) return ['ok' => false, 'error' => 'ルートパスが未設定です。'];

        try {
            if (!is_dir($root) && !@mkdir($root, 0777, true)) {
                throw new Exception("ルートディレクトリを作成できません: {$root}");
            }

            $vars = self::prepareVars($d);

            $skeletonBase = __DIR__ . '/stubs/skeleton';
            if (!is_dir($skeletonBase)) {
                throw new Exception("Skeleton directory not found: {$skeletonBase}");
            }

            self::replicateSkeleton($skeletonBase, $root, $vars, $d);

            $pubPath = trim($d['path_public'] ?? 'public', '/');
            if ($pubPath !== '' && $pubPath !== '.') {
                $htaccessContent = "# Generated by Fzr Setup\n"
                    . "<IfModule mod_authz_core.c>\n    Require all denied\n</IfModule>\n"
                    . "<IfModule !mod_authz_core.c>\n    Order deny,allow\n    Deny from all\n</IfModule>\n";
                @file_put_contents($root . '/.htaccess', $htaccessContent);
            }

            self::deployFrameworkCore($root, $d);

            if ($d['include_doc'] ?? false) {
                self::deployDocumentation($root);
            }

            return ['ok' => true];
        } catch (\Throwable $ex) {
            return ['ok' => false, 'error' => $ex->getMessage() . " at " . $ex->getFile() . ":" . $ex->getLine()];
        }
    }

    private static function replicateSkeleton(string $src, string $dst, array $vars, array $d): void
    {
        $directory = new \RecursiveDirectoryIterator($src, \RecursiveDirectoryIterator::SKIP_DOTS);
        $iterator  = new \RecursiveIteratorIterator($directory, \RecursiveIteratorIterator::SELF_FIRST);

        foreach ($iterator as $item) {
            $relPath = str_replace($src . DIRECTORY_SEPARATOR, '', $item->getPathname());

            foreach ($vars as $k => $v) {
                if (is_scalar($v)) {
                    $relPath = str_replace('{{' . strtoupper($k) . '}}', (string)$v, $relPath);
                }
            }

            $targetPath = $dst . DIRECTORY_SEPARATOR . $relPath;

            if ($item->isDir()) {
                if (!is_dir($targetPath)) @mkdir($targetPath, 0777, true);
            } else {
                if (str_ends_with($targetPath, '.stub')) {
                    $targetPath = substr($targetPath, 0, -5);
                }

                $content = file_get_contents($item->getPathname());
                foreach ($vars as $k => $v) {
                    if (is_scalar($v)) {
                        $content = str_replace('{{' . strtoupper($k) . '}}', (string)$v, $content);
                    }
                }

                $parent = dirname($targetPath);
                if (!is_dir($parent)) @mkdir($parent, 0777, true);

                file_put_contents($targetPath, $content);
            }
        }
    }

    private static function prepareVars(array $d): array
    {
        $appPath = trim($d['path_app']     ?? 'app',     '/');
        $pubPath = trim($d['path_public']  ?? 'public',  '/');
        $stoPath = trim($d['path_storage'] ?? 'storage', '/');
        $dbPath  = trim($d['path_db']      ?? 'db',      '/');

        $lang     = $d['lang']     ?? 'ja';
        $charset  = $d['charset']  ?? 'UTF-8';
        $timezone = $d['timezone'] ?? 'Asia/Tokyo';
        $driver   = $d['db_driver'] ?? 'sqlite';

        $sqlitePath = ($driver === 'sqlite') ? "sqlite_path = app.db" : "";

        $dbConfigMasked = '';
        $dbConfigReal   = '';
        if ($driver !== 'sqlite' && $driver !== 'none') {
            $port = (int)($d['db_port'] ?: ($driver === 'pgsql' ? 5432 : 3306));
            $dbConfigMasked = "host = \"****\"\nport = {$port}\ndatabase = \"****\"\nusername = \"****\"\npassword = \"****\"";
            $dbConfigReal   = "DB_HOST=\"{$d['db_host']}\"\nDB_PORT={$port}\nDB_DATABASE=\"{$d['db_database']}\"\nDB_USERNAME=\"{$d['db_username']}\"\nDB_PASSWORD=\"{$d['db_password']}\"";
        }

        if ($pubPath === '' || $pubPath === '.') {
            $upExpr = '__DIR__';
        } else {
            $levels = count(explode('/', trim($pubPath, '/')));
            $upExpr = $levels > 1 ? "dirname(__DIR__, $levels)" : 'dirname(__DIR__)';
        }

        $frameworkMode = $d['framework_mode'] ?? 'relative';
        $coreBase      = rtrim($d['path_core'] ?? dirname(dirname(dirname(__FILE__))), '/\\');
        $coreLoader    = '';
        switch ($frameworkMode) {
            case 'phar':
                $coreLoader = "require_once ABSPATH . '/fzr.phar';";
                break;
            case 'bundle':
                $coreLoader = "require_once ABSPATH . '/fzr.bundle.php';";
                break;
            case 'relative':
                $coreFile   = is_dir($coreBase) ? $coreBase . '/loader.php' : $coreBase;
                $coreLoader = "require_once " . var_export($coreFile, true) . ";";
                break;
        }

        $frameworkRequire = '';
        $repositories     = '';
        if ($frameworkMode === 'composer') {
            $frameworkRequire = ",\n        \"fzr/fw\": \"*\"";
            $repoUrl  = self::REPO_URL;
            $kitUrl   = 'https://github.com/t-ichi324/fzr-kit.git';
            $repositories = ",\n    \"repositories\": [\n        {\"type\": \"vcs\", \"url\": \"{$repoUrl}\"},\n        {\"type\": \"vcs\", \"url\": \"{$kitUrl}\"}\n    ]";
        }

        return [
            'APP_NAME'          => $d['app_name'],
            'APP_KEY'           => bin2hex(random_bytes(16)),
            'TIMEZONE'          => $timezone,
            'LANG'              => $lang,
            'CHARSET'           => $charset,
            'DEBUG'             => $d['debug_mode'] ? 'true' : 'false',
            'GENERATED_AT'      => date('Y-m-d H:i:s'),
            'PATH_APP'          => $appPath,
            'PATH_PUBLIC'       => $pubPath,
            'PATH_DB'           => $dbPath,
            'PATH_STORAGE'      => $stoPath,
            'PATH_TEMP'         => $stoPath . '/temp',
            'DB_DRIVER'         => $driver,
            'DB_SQLITE_PATH'    => $sqlitePath,
            'DB_CONFIG_MASKED'  => $dbConfigMasked,
            'DB_CONFIG_REAL'    => $dbConfigReal,
            'LOG_DEBUG'         => $d['debug_mode'] ? 'true' : 'false',
            'LOG_DB_SEL'        => $d['debug_mode'] ? 'true' : 'false',
            'UP_EXPR'           => $upExpr,
            'CORE_LOADER'       => $coreLoader,
            'FRAMEWORK_REQUIRE' => $frameworkRequire,
            'REPOSITORIES'      => $repositories,
            'CLASS_NAME'        => 'IndexController',
            'TITLE'             => 'Home',
            'VIEW'              => 'index',
        ];
    }

    private static function deployDocumentation(string $root): void
    {
        $fwRoot = dirname(__DIR__);
        $files  = ['README.md' => 'FZR_README.md', 'ENV.md' => 'FZR_ENV.md', 'AI.md' => 'FZR_AI.md'];
        foreach ($files as $srcName => $dstName) {
            $src = $fwRoot . DIRECTORY_SEPARATOR . $srcName;
            $dst = $root  . DIRECTORY_SEPARATOR . $dstName;
            if (file_exists($src)) @copy($src, $dst);
        }
    }

    private static function deployFrameworkCore(string $root, array $d): void
    {
        $mode     = $d['framework_mode'] ?? 'relative';
        $coreBase = rtrim($d['path_core'] ?? '', '/\\');

        if ($mode === 'phar') {
            $src = $coreBase . '/fzr.phar';
            $dst = $root . '/fzr.phar';
            if (!file_exists($src)) self::buildPhar($coreBase, $src);
            if (file_exists($src) && $src !== $dst) copy($src, $dst);
        } elseif ($mode === 'bundle') {
            $src = $coreBase . '/fzr.bundle.php';
            $dst = $root . '/fzr.bundle.php';
            self::buildBundle($coreBase, $src);
            if (file_exists($src) && $src !== $dst) copy($src, $dst);
        }
    }

    private static function buildBundle(string $coreBase, string $outFile): void
    {
        $srcPath = $coreBase . '/src';
        $incPath = $coreBase . '/inc';
        if (!is_dir($srcPath)) return;

        $content = "<?php\n/**\n * Fzr Framework Bundle (Auto-generated by Setup)\n */\n\n";
        $content .= "namespace {\n    if (!defined('ABSPATH')) define('ABSPATH', __DIR__);\n    if (!defined('FZR_BUNDLED')) define('FZR_BUNDLED', true);\n}\n\n";

        $files = array_merge(self::collectFiles($srcPath), self::collectFiles($incPath));
        foreach ($files as $path) {
            $code = file_get_contents($path);
            $code = preg_replace('/^<\?php\s*/i', '', $code);
            $namespace = '';
            if (preg_match('/namespace\s+([^;{\s]+)\s*;/i', $code, $m)) {
                $namespace = $m[1];
                $code = preg_replace('/namespace\s+([^;{\s]+)\s*;/i', '', $code, 1);
            }
            $code = trim($code);
            $fileInfo = "// File: " . basename($path) . "\n";
            if ($namespace) {
                $content .= "namespace {$namespace} {\n{$fileInfo}{$code}\n}\n\n";
            } else {
                $content .= "namespace {\n{$fileInfo}{$code}\n}\n\n";
            }
        }
        file_put_contents($outFile, $content);
    }

    private static function buildPhar(string $coreBase, string $outFile): void
    {
        if (ini_get('phar.readonly')) return;
        try {
            $p = new \Phar($outFile, 0, 'fzr.phar');
            $p->startBuffering();
            foreach (['src' => $coreBase . '/src', 'inc' => $coreBase . '/inc'] as $prefix => $dir) {
                if (!is_dir($dir)) continue;
                $iter = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \RecursiveDirectoryIterator::SKIP_DOTS));
                foreach ($iter as $file) {
                    if ($file->isFile() && $file->getExtension() === 'php') {
                        $rel = $prefix . '/' . str_replace($dir . DIRECTORY_SEPARATOR, '', $file->getPathname());
                        $p->addFile($file->getPathname(), str_replace('\\', '/', $rel));
                    }
                }
            }
            $stub = "<?php Phar::mapPhar('fzr.phar'); spl_autoload_register(function(\$c){ if(strpos(\$c,'Fzr\\\\')===0){ \$f='phar://fzr.phar/src/'.str_replace('\\\\','/',substr(\$c,4)).'.php'; if(file_exists(\$f))require \$f; } }); if(file_exists('phar://fzr.phar/inc/helpers.php'))require 'phar://fzr.phar/inc/helpers.php'; if(file_exists('phar://fzr.phar/inc/aliases.php'))require 'phar://fzr.phar/inc/aliases.php'; __HALT_COMPILER();";
            $p->setStub($stub);
            $p->stopBuffering();
        } catch (\Throwable $e) {
        }
    }

    private static function collectFiles(string $dir): array
    {
        if (!is_dir($dir)) return [];
        $files = [];
        $iter  = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \RecursiveDirectoryIterator::SKIP_DOTS));
        foreach ($iter as $file) {
            if ($file->isFile() && $file->getExtension() === 'php') $files[] = $file->getPathname();
        }
        usort($files, function ($a, $b) {
            $priority = ['Config.php', 'Path.php', 'Env.php', 'Context.php', 'Model.php', 'Controller.php', 'Loader.php', 'Engine.php', 'helpers.php'];
            foreach ($priority as $p) {
                if (str_ends_with($a, $p)) return -1;
                if (str_ends_with($b, $p)) return 1;
            }
            return strcmp($a, $b);
        });
        return $files;
    }
}
