<?php

namespace Fzr\Tool;

use Exception;
use PDO;

/**
 * Fzr Core Scaffolder
 *
 * プロジェクトのディレクトリ構造と初期ファイルをスケルトン（tools/stubs/skeleton/）から生成します。
 */
class Scaffolder
{
    /** GitHub Repository URL */
    const REPO_URL = 'https://github.com/t-ichi324/fzr-fw.git';

    /**
     * インストール済みかチェック
     */
    public static function isInstalled(string $root, string $appPath = 'app'): bool
    {
        $app = trim($appPath, '/');
        return file_exists($root . '/' . $app . '/app.ini')
            || file_exists($root . '/app.ini');
    }

    /**
     * インストール実行
     */
    public static function scaffold(array $d): array
    {
        $root = rtrim($d['path_root'] ?? '', '/\\');
        if (!$root) return ['ok' => false, 'error' => 'ルートパスが未設定です。'];

        try {
            if (!is_dir($root) && !@mkdir($root, 0777, true)) {
                throw new Exception("ルートディレクトリを作成できません: {$root}");
            }

            // ── 1. 置換変数の準備 ─────────────────────────────────
            $vars = self::prepareVars($d);

            // ── 2. スケルトンの展開 ───────────────────────────────
            $skeletonBase = __DIR__ . '/stubs/skeleton';
            if (!is_dir($skeletonBase)) {
                throw new Exception("Skeleton directory not found: {$skeletonBase}");
            }

            self::replicateSkeleton($skeletonBase, $root, $vars, $d);

            // ── 3. ルートガードの動的生成 ─────────────────────────────
            // Public がルートでない場合のみ、プロジェクトルートへの直接アクセスを拒否する
            $pubPath = trim($d['path_public'] ?? 'public', '/');
            if ($pubPath !== '' && $pubPath !== '.') {
                $htaccessContent = "# Generated by Fzr Setup\n"
                    . "<IfModule mod_authz_core.c>\n    Require all denied\n</IfModule>\n"
                    . "<IfModule !mod_authz_core.c>\n    Order deny,allow\n    Deny from all\n</IfModule>\n";
                @file_put_contents($root . '/.htaccess', $htaccessContent);
            }

            // ── 4. フレームワーク本体の配置 ─────────────────────────
            // これはスケルトン走査外のバイナリコピーなので個別に実行
            self::deployFrameworkCore($root, $d);

            // ── 5. ドキュメントの配置 ─────────────────────────────
            if ($d['include_doc'] ?? false) {
                self::deployDocumentation($root);
            }

            return ['ok' => true];
        } catch (\Throwable $ex) {
            return ['ok' => false, 'error' => $ex->getMessage() . " at " . $ex->getFile() . ":" . $ex->getLine()];
        }
    }

    /**
     * スケルトンディレクトリ構造を再帰的にコピーし、プレースホルダーを置換する
     */
    private static function replicateSkeleton(string $src, string $dst, array $vars, array $d): void
    {
        $directory = new \RecursiveDirectoryIterator($src, \RecursiveDirectoryIterator::SKIP_DOTS);
        $iterator = new \RecursiveIteratorIterator($directory, \RecursiveIteratorIterator::SELF_FIRST);

        $pubPath = trim($d['path_public'] ?? 'public', '/');
        $isPublicRoot = ($pubPath === '' || $pubPath === '.');

        foreach ($iterator as $item) {
            $relPath = str_replace($src . DIRECTORY_SEPARATOR, '', $item->getPathname());

            // パス名の置換 ({{PATH_APP}} 等)
            foreach ($vars as $k => $v) {
                if (is_scalar($v)) {
                    $relPath = str_replace('{{' . strtoupper($k) . '}}', (string)$v, $relPath);
                }
            }

            // 特定のプリセットに無関係なデプロイスクリプトを除外
            $preset = $d['preset'] ?? 'standard';
            if ($preset === 'standard' && str_contains($relPath, 'deploy-gcp')) {
                continue;
            }

            $targetPath = $dst . DIRECTORY_SEPARATOR . $relPath;

            if ($item->isDir()) {
                if (!is_dir($targetPath)) @mkdir($targetPath, 0777, true);
            } else {
                // ファイル名の .stub 拡張子を除去
                if (str_ends_with($targetPath, '.stub')) {
                    $targetPath = substr($targetPath, 0, -5);
                }

                $content = file_get_contents($item->getPathname());
                foreach ($vars as $k => $v) {
                    if (is_scalar($v)) {
                        $content = str_replace('{{' . strtoupper($k) . '}}', (string)$v, $content);
                    }
                }

                $parent = dirname($targetPath);
                if (!is_dir($parent)) @mkdir($parent, 0777, true);

                file_put_contents($targetPath, $content);
            }
        }
    }

    /**
     * テンプレート置換用の変数を組み立てる
     */
    private static function prepareVars(array $d): array
    {
        $appPath = trim($d['path_app']     ?? 'app',     '/');
        $pubPath = trim($d['path_public']  ?? 'public',  '/');
        $stoPath = trim($d['path_storage'] ?? 'storage', '/');
        $dbPath  = trim($d['path_db']      ?? 'db',      '/');

        $lang    = $d['lang'] ?? 'ja';
        $charset = $d['charset'] ?? 'UTF-8';
        $timezone = $d['timezone'] ?? 'Asia/Tokyo';

        $preset = $d['preset'] ?? 'standard';
        $driver = $d['db_driver'] ?? 'sqlite';

        // app.ini 用の動的な値
        $sqlitePath = ($driver === 'sqlite') ? "sqlite_path = app.db" : "";
        $dbConfigMasked = "";
        $dbConfigReal = "";
        if ($driver !== 'sqlite' && $driver !== 'none') {
            $port = (int)($d['db_port'] ?: ($driver === 'pgsql' ? 5432 : 3306));
            $dbConfigMasked = "host = \"****\"\nport = {$port}\ndatabase = \"****\"\nusername = \"****\"\npassword = \"****\"";
            if ($driver === 'pgsql' && !empty($d['db_schema'])) $dbConfigMasked .= "\nschema = public";

            $dbConfigReal = "DB_HOST=\"{$d['db_host']}\"\nDB_PORT={$port}\nDB_DATABASE=\"{$d['db_database']}\"\nDB_USERNAME=\"{$d['db_username']}\"\nDB_PASSWORD=\"{$d['db_password']}\"";
        }

        $isStateless = ($preset !== 'standard');
        $gcpIni = '';
        if ($preset === 'gcp' && !empty($d['gcs_bucket'])) {
            $bucket  = $d['gcs_bucket'];
            $keyLine = !empty($d['gcs_key_path']) ? "\nkey_file = \"{$d['gcs_key_path']}\"" : '';
            $gcpIni  = "; GCS ストレージ設定 (GCP preset)\n";
            $gcpIni .= "; ローカル開発時も .env に同じ値を設定することで GCS を利用可能\n";
            $gcpIni .= "[storage.public]\n";
            $gcpIni .= "driver = gcs\n";
            $gcpIni .= "bucket = \"{$bucket}\"{$keyLine}\n";
            $gcpIni .= "\n[storage.private]\n";
            $gcpIni .= "driver = gcs\n";
            $gcpIni .= "bucket = \"{$bucket}\"\n";
            $gcpIni .= "root = private{$keyLine}";
        }

        // Docker 用の拡張・ライブラリ判定
        $dockerSysLibs = ($driver === 'pgsql') ? "libpq-dev" : "";
        $dockerPhpExts = match ($driver) {
            'mysql' => 'pdo_mysql',
            'pgsql' => 'pdo_pgsql',
            default => '',
        };

        // Redis インストール: デフォルトはコメントアウト。Memorystore 等を使う場合は解除。
        $dockerRedisInstall = "# Redis 拡張: Memorystore 等を使う場合はコメントを解除してください。\n# RUN pecl install redis && docker-php-ext-enable redis\n";

        // GCS composer 依存 (GCP preset のみ追加)
        $composerGcsRequire = ($preset === 'gcp' && !empty($d['gcs_bucket']))
            ? ",\n        \"google/cloud-storage\": \"^1.39\""
            : '';

        // deploy スクリプト用 Redis コメント（セッションは cookie driver がデフォルト、Redis は任意追加）
        $deployRedisEnvSh  = "# セッションは暗号化 cookie で動作します（外部依存なし）。\n# Redis (Memorystore 等) を使う場合は以下を追加してください:\n# ENV_VARS=\"\${ENV_VARS},REDIS_HOST=<host>,REDIS_PORT=6379\"";
        $deployRedisEnvBat = "rem セッションは暗号化 cookie で動作します（外部依存なし）。\nrem Redis (Memorystore 等) を使う場合は以下を追加してください:\nrem set ENV_VARS=%ENV_VARS%,REDIS_HOST=<host>,REDIS_PORT=6379";

        // .env 用のデプロイメモ（非機密情報のみ。パスワードは含めない）
        $deployMemo = '';
        if ($preset === 'gcp') {
            $deployMemo .= '# Deploy  : GCP Cloud Run' . "\n";
            if (!empty($d['gcp_project_id'])) $deployMemo .= '# Project : ' . $d['gcp_project_id'] . "\n";
            if (!empty($d['deploy_service'])) $deployMemo .= '# Service : ' . $d['deploy_service'] . "\n";
            if (!empty($d['deploy_region']))  $deployMemo .= '# Region  : ' . $d['deploy_region']  . "\n";
        }
        if ($driver !== 'none') {
            $deployMemo .= '# DB      : ' . $driver;
            if ($driver === 'sqlite') {
                $deployMemo .= "\n";
            } else {
                $host = $d['db_host'] ?? '';
                $port = $d['db_port'] ?? '';
                $db   = $d['db_database'] ?? '';
                $user = $d['db_username'] ?? '';
                $deployMemo .= " ({$user}@{$host}:{$port}/{$db})" . "\n";
            }
        }
        if (!empty($d['gcs_bucket'])) {
            $deployMemo .= '# Storage : GCS bucket=' . $d['gcs_bucket'];
            if (!empty($d['gcs_key_path'])) $deployMemo .= ' key=' . $d['gcs_key_path'];
            $deployMemo .= "\n";
        } else {
            $deployMemo .= '# Storage : local (' . $stoPath . ")\n";
        }

        // public/index.php 用のディレクトリ深度計算
        if ($pubPath === '' || $pubPath === '.') {
            $upExpr = '__DIR__';
        } else {
            $levels = count(explode('/', trim($pubPath, '/')));
            $upExpr = $levels > 1 ? "dirname(__DIR__, $levels)" : 'dirname(__DIR__)';
        }

        // コアローダーの構築
        $frameworkMode = $d['framework_mode'] ?? 'relative';
        $coreBase      = rtrim($d['path_core'] ?? dirname(dirname(dirname(__FILE__))), '/\\');
        $coreLoader = "";
        switch ($frameworkMode) {
            case 'phar':
                $coreLoader = "require_once ABSPATH . '/fzr.phar';";
                break;
            case 'bundle':
                $coreLoader = "require_once ABSPATH . '/fzr.bundle.php';";
                break;
            case 'relative':
                $coreFile   = is_dir($coreBase) ? $coreBase . '/loader.php' : $coreBase;
                $fzrLoader  = var_export($coreFile, true);
                $coreLoader = "require_once {$fzrLoader};";
                break;
        }

        // composer.json 依存関係
        $frameworkRequire = "";
        $repositories = "";
        if ($frameworkMode === 'composer') {
            $fzrCorePath = dirname(dirname(__FILE__));
            $frameworkRequire = ",\n        \"fzr/fw\": \"*\"";
            $repoUrl = self::REPO_URL;
            $kitUrl  = 'https://github.com/t-ichi324/fzr-kit.git';
            $repositories = ",\n    \"repositories\": [\n        {\"type\": \"path\", \"url\": " . json_encode($fzrCorePath) . ", \"options\": {\"symlink\": false}},\n        {\"type\": \"vcs\", \"url\": \"{$repoUrl}\"},\n        {\"type\": \"vcs\", \"url\": \"{$kitUrl}\"}\n    ]";
        }

        return [
            'APP_NAME'         => $d['app_name'],
            'APP_KEY'          => bin2hex(random_bytes(16)),
            'TIMEZONE'         => $timezone,
            'LANG'             => $lang,
            'CHARSET'          => $charset,
            'DEBUG'            => $d['debug_mode'] ? 'true' : 'false',
            'PRESET'           => $preset,
            'GENERATED_AT'     => date('Y-m-d H:i:s'),
            'PATH_APP'         => $appPath,
            'PATH_PUBLIC'      => $pubPath,
            'PATH_DB'          => $dbPath,
            'PATH_STORAGE'     => $stoPath,
            'PATH_TEMP'        => $stoPath . '/temp',
            'DB_DRIVER'        => $driver,
            'DB_SQLITE_PATH'   => $sqlitePath,
            'DB_CONFIG_MASKED' => $dbConfigMasked,
            'DB_CONFIG_REAL'   => $dbConfigReal,
            'LOG_ACCESS'       => $isStateless ? 'false' : 'true',
            'LOG_DEBUG'        => $d['debug_mode'] ? 'true' : 'false',
            'LOG_DB_SEL'       => $d['debug_mode'] ? 'true' : 'false',
            'UP_EXPR'          => $upExpr,
            'CORE_LOADER'      => $coreLoader,
            'FRAMEWORK_REQUIRE' => $frameworkRequire,
            'REPOSITORIES'     => $repositories,
            'CLASS_NAME'       => 'IndexController', // デフォルト
            'TITLE'            => 'Home',            // デフォルト
            'VIEW'             => 'index',           // デフォルト
            'DEPLOY_SERVICE'   => $d['deploy_service'] ?? '',
            'DEPLOY_REGION'    => $d['deploy_region'] ?? '',
            'GCP_PROJECT_ID'   => $d['gcp_project_id'] ?? '',
            'GCP_INI'              => $gcpIni,
            'DOCKER_SYS_LIBS'      => $dockerSysLibs,
            'DOCKER_PHP_EXTS'      => $dockerPhpExts,
            'DOCKER_REDIS_INSTALL'   => $dockerRedisInstall,
            'COMPOSER_GCS_REQUIRE'   => $composerGcsRequire,
            'DEPLOY_REDIS_ENV_SH'    => $deployRedisEnvSh,
            'DEPLOY_REDIS_ENV_BAT'   => $deployRedisEnvBat,
            'DEPLOY_MEMO'            => $deployMemo,
        ];
    }

    /**
     * README.md / ENV.md / AI.md をプロジェクトルートに配備する
     */
    private static function deployDocumentation(string $root): void
    {
        $fwRoot = dirname(__DIR__);

        // フレームワーク側のドキュメントをプロジェクトルートにコピーする
        // ユーザーの指示「フォルダを作らずrootに」に従い、ルートに展開する。
        $files = [
            'README.md' => 'FZR_README.md',
            'ENV.md'    => 'FZR_ENV.md',
            'AI.md'     => 'FZR_AI.md'
        ];
        
        foreach ($files as $srcName => $dstName) {
            $src = $fwRoot . DIRECTORY_SEPARATOR . $srcName;
            $dst = $root . DIRECTORY_SEPARATOR . $dstName;
            if (file_exists($src)) {
                @copy($src, $dst);
            }
        }
    }

    /**
     * phar / bundle モード時にフレームワーク本体をプロジェクトルートへコピーする。
     */
    private static function deployFrameworkCore(string $root, array $d): void
    {
        $mode     = $d['framework_mode'] ?? 'relative';
        $coreBase = rtrim($d['path_core'] ?? '', '/\\');

        if ($mode === 'phar') {
            $src = $coreBase . '/fzr.phar';
            $dst = $root . '/fzr.phar';
            if (!file_exists($src)) self::buildPhar($coreBase, $src);
            if (file_exists($src) && $src !== $dst) copy($src, $dst);
        } elseif ($mode === 'bundle') {
            $src = $coreBase . '/fzr.bundle.php';
            $dst = $root . '/fzr.bundle.php';
            // 手元の「ソース」の修正を確実に反映させるため、init 時は常に再ビルドする
            self::buildBundle($coreBase, $src);
            if (file_exists($src) && $src !== $dst) copy($src, $dst);
        }
    }

    /**
     * フレームワークを 1 ファイルにバンドルする（Scaffolder用簡易版）
     */
    private static function buildBundle(string $coreBase, string $outFile): void
    {
        $srcPath = $coreBase . '/src';
        $incPath = $coreBase . '/inc';
        if (!is_dir($srcPath)) return;

        $content = "<?php\n/**\n * Fzr Framework Bundle (Auto-generated by Setup)\n */\n\n";
        $content .= "namespace {\n    if (!defined('ABSPATH')) define('ABSPATH', __DIR__);\n    if (!defined('FZR_BUNDLED')) define('FZR_BUNDLED', true);\n}\n\n";

        $files = array_merge(self::collectFiles($srcPath), self::collectFiles($incPath));
        foreach ($files as $path) {
            $code = file_get_contents($path);
            $code = preg_replace('/^<\?php\s*/i', '', $code);
            $namespace = '';
            if (preg_match('/namespace\s+([^;{\s]+)\s*;/i', $code, $m)) {
                $namespace = $m[1];
                $code = preg_replace('/namespace\s+([^;{\s]+)\s*;/i', '', $code, 1);
            }
            $code = trim($code);
            $fileInfo = "// File: " . basename($path) . "\n";
            if ($namespace) {
                $content .= "namespace {$namespace} {\n{$fileInfo}{$code}\n}\n\n";
            } else {
                $content .= "namespace {\n{$fileInfo}{$code}\n}\n\n";
            }
        }
        file_put_contents($outFile, $content);
    }

    /**
     * フレームワークを Phar にビルドする（Scaffolder用簡易版）
     */
    private static function buildPhar(string $coreBase, string $outFile): void
    {
        if (ini_get('phar.readonly')) return;
        try {
            $p = new \Phar($outFile, 0, 'fzr.phar');
            $p->startBuffering();
            $srcPath = $coreBase . '/src';
            $incPath = $coreBase . '/inc';
            foreach (['src' => $srcPath, 'inc' => $incPath] as $prefix => $dir) {
                if (!is_dir($dir)) continue;
                $iter = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \RecursiveDirectoryIterator::SKIP_DOTS));
                foreach ($iter as $file) {
                    if ($file->isFile() && $file->getExtension() === 'php') {
                        $rel = $prefix . '/' . str_replace($dir . DIRECTORY_SEPARATOR, '', $file->getPathname());
                        $rel = str_replace('\\', '/', $rel);
                        $p->addFile($file->getPathname(), $rel);
                    }
                }
            }
            $stub = "<?php Phar::mapPhar('fzr.phar'); spl_autoload_register(function(\$c){ if(strpos(\$c,'Fzr\\\\')===0){ \$f='phar://fzr.phar/src/'.str_replace('\\\\','/',substr(\$c,4)).'.php'; if(file_exists(\$f))require \$f; } }); if(file_exists('phar://fzr.phar/inc/helpers.php'))require 'phar://fzr.phar/inc/helpers.php'; if(file_exists('phar://fzr.phar/inc/aliases.php'))require 'phar://fzr.phar/inc/aliases.php'; __HALT_COMPILER();";
            $p->setStub($stub);
            $p->stopBuffering();
        } catch (\Throwable $e) {
        }
    }

    private static function collectFiles(string $dir): array
    {
        if (!is_dir($dir)) return [];
        $files = [];
        $iter = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir, \RecursiveDirectoryIterator::SKIP_DOTS));
        foreach ($iter as $file) {
            if ($file->isFile() && $file->getExtension() === 'php') $files[] = $file->getPathname();
        }
        usort($files, function ($a, $b) {
            $priority = ['Config.php', 'Path.php', 'Env.php', 'Context.php', 'Model.php', 'Controller.php', 'Loader.php', 'Engine.php', 'helpers.php'];
            foreach ($priority as $p) {
                if (str_ends_with($a, $p)) return -1;
                if (str_ends_with($b, $p)) return 1;
            }
            return strcmp($a, $b);
        });
        return $files;
    }
}
